---
# tasks file for roles/zabbix_api
- name: "Run the API calls to Zabbix Server"
  vars:
    gather_facts: false
    ansible_user: "{{ zabbix_api_login_user }}"
    ansible_httpapi_use_ssl: "{{ zabbix_api_use_ssl }}"
    ansible_network_os: community.zabbix.zabbix
    ansible_connection: httpapi
    # Can't think of a way to make http_login_* vars be undefined -(
    http_login_user: "{{ zabbix_api_http_user | default(-42) }}"
    http_login_password: "{{ zabbix_api_http_password | default(-42) }}"
  ansible.builtin.include_tasks: api.yml
  when:
    - (zabbix_api_create_hostgroup | bool) or (zabbix_api_create_hosts | bool)